"""
Tests for Sudoku Puzzle Solutions resource/endpoint.
"""
from backend.resources.sudoku_solution import SudokuPuzzleSolution
from backend import app
from backend.config import UnitTestingConfig
from flask import g
from tests.unit.mocks import user, mock_no_puzzles_for_player, \
    mock_single_puzzles_for_player, mock_get_puzzle

app.config.from_object(UnitTestingConfig)


def test_sudoku_puzzles_get_solution_not_associated(user, mock_no_puzzles_for_player):
    """
    If a player attempts to get the solution for a puzzle that they are
    not associated with, the request should fail.
    """
    with app.app_context():
        g.user = user
        puzzle_solution_resource = SudokuPuzzleSolution()
        result = puzzle_solution_resource.get(2)

    expected = ({'message': "Puzzle requested does not exist or is not "
                    "associated with user Jane Doe (id = 1)"}, 404)
    assert result == expected


def test_sudoku_puzzles_get_solution_not_associated_2(user, mock_single_puzzles_for_player):
    """
    If a player attempts to get the solution for a puzzle that they are
    not associated with, the request should fail.
    """
    with app.app_context():
        g.user = user
        puzzle_solution_resource = SudokuPuzzleSolution()
        result = puzzle_solution_resource.get(2)

    expected = ({'message': "Puzzle requested does not exist or is not "
                    "associated with user Jane Doe (id = 1)"}, 404)
    assert result == expected


def test_sudoku_puzzles_get_solution(user, mock_single_puzzles_for_player, mock_get_puzzle):
    """
    If a player attempts to get the solution for a puzzle that they are
    associated with, the request should succeed.
    """
    with app.app_context():
        g.user = user
        puzzle_solution_resource = SudokuPuzzleSolution()
        result = puzzle_solution_resource.get(1)

    # this is just basically a deterministic board; a board with 0 static pieces
    expected = {'solved_puzzle': {'puzzle_id': None, 'completed': True, 'difficulty': 0.5,
                                  'point_value': 90,
                                  'pieces': [
                                      {'x_coordinate': 0, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 1, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 2, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 3, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 4, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 5, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 6, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 7, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 8, 'y_coordinate': 0, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 0, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 1, 'y_coordinate': 1, 'static_piece': True,
                                       'value': 3},
                                      {'x_coordinate': 2, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 3, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 4, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 5, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 6, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 7, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 8, 'y_coordinate': 1, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 0, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 1, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 2, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 3, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 4, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 5, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 6, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 7, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 8, 'y_coordinate': 2, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 0, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 1, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 2, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 3, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 4, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 5, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 6, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 7, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 8, 'y_coordinate': 3, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 0, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 1, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 2, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 3, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 4, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 5, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 6, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 7, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 8, 'y_coordinate': 4, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 0, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 1, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 2, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 3, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 4, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 5, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 6, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 7, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 8, 'y_coordinate': 5, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 0, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 1, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 2, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 3, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 4, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 5, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 6, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 7, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 8, 'y_coordinate': 6, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 0, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 1, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 2, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 2},
                                      {'x_coordinate': 3, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 4, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 5, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 6, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 7, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 8, 'y_coordinate': 7, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 0, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 9},
                                      {'x_coordinate': 1, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 6},
                                      {'x_coordinate': 2, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 8},
                                      {'x_coordinate': 3, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 4},
                                      {'x_coordinate': 4, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 3},
                                      {'x_coordinate': 5, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 1},
                                      {'x_coordinate': 6, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 5},
                                      {'x_coordinate': 7, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 7},
                                      {'x_coordinate': 8, 'y_coordinate': 8, 'static_piece': False,
                                       'value': 2}]},
                'discrepancy': [{'x_coordinate': 0, 'y_coordinate': 0},
                                {'x_coordinate': 1, 'y_coordinate': 0},
                                {'x_coordinate': 2, 'y_coordinate': 0},
                                {'x_coordinate': 3, 'y_coordinate': 0},
                                {'x_coordinate': 4, 'y_coordinate': 0},
                                {'x_coordinate': 5, 'y_coordinate': 0},
                                {'x_coordinate': 6, 'y_coordinate': 0},
                                {'x_coordinate': 7, 'y_coordinate': 0},
                                {'x_coordinate': 8, 'y_coordinate': 0},
                                {'x_coordinate': 0, 'y_coordinate': 1},
                                {'x_coordinate': 2, 'y_coordinate': 1},
                                {'x_coordinate': 3, 'y_coordinate': 1},
                                {'x_coordinate': 4, 'y_coordinate': 1},
                                {'x_coordinate': 5, 'y_coordinate': 1},
                                {'x_coordinate': 6, 'y_coordinate': 1},
                                {'x_coordinate': 7, 'y_coordinate': 1},
                                {'x_coordinate': 8, 'y_coordinate': 1},
                                {'x_coordinate': 0, 'y_coordinate': 2},
                                {'x_coordinate': 1, 'y_coordinate': 2},
                                {'x_coordinate': 2, 'y_coordinate': 2},
                                {'x_coordinate': 3, 'y_coordinate': 2},
                                {'x_coordinate': 4, 'y_coordinate': 2},
                                {'x_coordinate': 5, 'y_coordinate': 2},
                                {'x_coordinate': 6, 'y_coordinate': 2},
                                {'x_coordinate': 7, 'y_coordinate': 2},
                                {'x_coordinate': 8, 'y_coordinate': 2},
                                {'x_coordinate': 0, 'y_coordinate': 3},
                                {'x_coordinate': 1, 'y_coordinate': 3},
                                {'x_coordinate': 2, 'y_coordinate': 3},
                                {'x_coordinate': 3, 'y_coordinate': 3},
                                {'x_coordinate': 4, 'y_coordinate': 3},
                                {'x_coordinate': 5, 'y_coordinate': 3},
                                {'x_coordinate': 6, 'y_coordinate': 3},
                                {'x_coordinate': 7, 'y_coordinate': 3},
                                {'x_coordinate': 8, 'y_coordinate': 3},
                                {'x_coordinate': 0, 'y_coordinate': 4},
                                {'x_coordinate': 1, 'y_coordinate': 4},
                                {'x_coordinate': 2, 'y_coordinate': 4},
                                {'x_coordinate': 3, 'y_coordinate': 4},
                                {'x_coordinate': 4, 'y_coordinate': 4},
                                {'x_coordinate': 5, 'y_coordinate': 4},
                                {'x_coordinate': 6, 'y_coordinate': 4},
                                {'x_coordinate': 7, 'y_coordinate': 4},
                                {'x_coordinate': 8, 'y_coordinate': 4},
                                {'x_coordinate': 0, 'y_coordinate': 5},
                                {'x_coordinate': 1, 'y_coordinate': 5},
                                {'x_coordinate': 2, 'y_coordinate': 5},
                                {'x_coordinate': 3, 'y_coordinate': 5},
                                {'x_coordinate': 4, 'y_coordinate': 5},
                                {'x_coordinate': 5, 'y_coordinate': 5},
                                {'x_coordinate': 6, 'y_coordinate': 5},
                                {'x_coordinate': 7, 'y_coordinate': 5},
                                {'x_coordinate': 8, 'y_coordinate': 5},
                                {'x_coordinate': 0, 'y_coordinate': 6},
                                {'x_coordinate': 1, 'y_coordinate': 6},
                                {'x_coordinate': 2, 'y_coordinate': 6},
                                {'x_coordinate': 3, 'y_coordinate': 6},
                                {'x_coordinate': 4, 'y_coordinate': 6},
                                {'x_coordinate': 5, 'y_coordinate': 6},
                                {'x_coordinate': 6, 'y_coordinate': 6},
                                {'x_coordinate': 7, 'y_coordinate': 6},
                                {'x_coordinate': 8, 'y_coordinate': 6},
                                {'x_coordinate': 0, 'y_coordinate': 7},
                                {'x_coordinate': 1, 'y_coordinate': 7},
                                {'x_coordinate': 2, 'y_coordinate': 7},
                                {'x_coordinate': 3, 'y_coordinate': 7},
                                {'x_coordinate': 4, 'y_coordinate': 7},
                                {'x_coordinate': 5, 'y_coordinate': 7},
                                {'x_coordinate': 6, 'y_coordinate': 7},
                                {'x_coordinate': 7, 'y_coordinate': 7},
                                {'x_coordinate': 8, 'y_coordinate': 7},
                                {'x_coordinate': 0, 'y_coordinate': 8},
                                {'x_coordinate': 1, 'y_coordinate': 8},
                                {'x_coordinate': 2, 'y_coordinate': 8},
                                {'x_coordinate': 3, 'y_coordinate': 8},
                                {'x_coordinate': 4, 'y_coordinate': 8},
                                {'x_coordinate': 5, 'y_coordinate': 8},
                                {'x_coordinate': 6, 'y_coordinate': 8},
                                {'x_coordinate': 7, 'y_coordinate': 8},
                                {'x_coordinate': 8, 'y_coordinate': 8}]}
    assert result == expected
